
import React, { useEffect, useState } from 'react';
import { CapacityReportItem } from '../types';
import { fetchCapacityReport } from '../services/api';
import { FileText, TrendingDown, Network, Activity } from 'lucide-react';

interface Props {
    isDarkMode: boolean;
}

const ReportView: React.FC<Props> = ({ isDarkMode }) => {
    const [report, setReport] = useState<CapacityReportItem[]>([]);
    const [activeTab, setActiveTab] = useState<'capacity' | 'traffic' | 'loss'>('capacity');
    const [selectedImage, setSelectedImage] = useState<string | null>(null);

    useEffect(() => {
        fetchCapacityReport().then(setReport);
    }, []);

    const API_BASE_URL = 'http://localhost:5000/api';

    return (
        <div className="w-full h-full flex flex-col gap-8 p-8 overflow-y-auto custom-scrollbar">

            {/* Header */}
            <div className="flex items-center justify-between shrink-0">
                <div>
                    <h2 className="text-3xl font-black text-emerald-950 dark:text-emerald-50 tracking-tighter uppercase italic">
                        Phase 2: <span className="text-emerald-600">Verification Report</span>
                    </h2>
                    <p className="text-sm text-emerald-800/60 dark:text-emerald-400/60 font-medium mt-1">
                        Offline analysis results generated by topology.py
                    </p>
                </div>

                {/* Tabs */}
                <div className="flex gap-2 p-1.5 bg-emerald-900/5 dark:bg-white/5 rounded-2xl border border-emerald-500/10 backdrop-blur-sm">
                    {[
                        { id: 'capacity', label: 'Capacity Plan', icon: FileText },
                        { id: 'traffic', label: 'Traffic Analysis', icon: Activity },
                        { id: 'loss', label: 'Topology Check', icon: Network },
                    ].map(tab => (
                        <button
                            key={tab.id}
                            onClick={() => setActiveTab(tab.id as any)}
                            className={`
                 flex items-center gap-2 px-4 py-2.5 rounded-xl text-xs font-black uppercase tracking-wider transition-all
                 ${activeTab === tab.id
                                    ? 'bg-emerald-600 text-white shadow-lg shadow-emerald-600/20'
                                    : 'text-emerald-900/40 dark:text-emerald-500/40 hover:bg-emerald-500/10'}
               `}
                        >
                            <tab.icon className="w-4 h-4" />
                            {tab.label}
                        </button>
                    ))}
                </div>
            </div>

            {/* Content Area */}
            <div className="flex-1 bg-white/70 dark:bg-royal-950/40 border border-emerald-500/10 rounded-[2.5rem] shadow-2xl backdrop-blur-xl p-8 relative min-h-0 overflow-y-auto custom-scrollbar">
                <div className="absolute inset-0 pointer-events-none opacity-[0.03]"
                    style={{ backgroundImage: `radial-gradient(#10b981 1.5px, transparent 1.5px)`, backgroundSize: '24px 24px' }}>
                </div>

                {activeTab === 'capacity' && (
                    <div className="relative z-10 w-full">
                        <table className="w-full text-left border-collapse">
                            <thead>
                                <tr className="border-b border-emerald-500/20">
                                    <th className="p-4 text-[10px] font-black text-emerald-900/40 dark:text-emerald-500/40 uppercase tracking-[0.2em]">Link ID</th>
                                    <th className="p-4 text-[10px] font-black text-emerald-900/40 dark:text-emerald-500/40 uppercase tracking-[0.2em]">Connected Cells</th>
                                    <th className="p-4 text-[10px] font-black text-emerald-900/40 dark:text-emerald-500/40 uppercase tracking-[0.2em]">Peak Load (No Buffer)</th>
                                    <th className="p-4 text-[10px] font-black text-emerald-600 dark:text-emerald-400 uppercase tracking-[0.2em]">Optimal (With Buffer)</th>
                                    <th className="p-4 text-[10px] font-black text-emerald-900/40 dark:text-emerald-500/40 uppercase tracking-[0.2em]">Est. Savings</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-emerald-500/10">
                                {report.map((row) => (
                                    <tr key={row.Link_ID} className="group hover:bg-emerald-500/5 transition-colors">
                                        <td className="p-6 font-mono font-bold text-emerald-900 dark:text-emerald-100">L-{row.Link_ID}</td>
                                        <td className="p-6 text-xs font-mono text-emerald-800/70 dark:text-emerald-300/70 max-w-xs truncate" title={row.Cells}>
                                            {row.Cells}
                                        </td>
                                        <td className="p-6 font-mono text-emerald-900/60 dark:text-emerald-500">{row.Peak_Capacity_Gbps} Gbps</td>
                                        <td className="p-6">
                                            <span className="inline-flex items-center gap-2 px-3 py-1 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 rounded-lg font-mono font-bold border border-emerald-500/20">
                                                {row.Optimal_Capacity_Gbps} Gbps
                                            </span>
                                        </td>
                                        <td className="p-6">
                                            <div className="flex items-center gap-2 text-emerald-600 font-bold">
                                                <TrendingDown className="w-4 h-4" />
                                                {row.Savings_Pct}%
                                            </div>
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                        {report.length === 0 && (
                            <div className="p-12 text-center text-emerald-900/30 dark:text-emerald-50/20 font-black italic uppercase">
                                No report data found. Run phase 2 logic first.
                            </div>
                        )}
                    </div>
                )}

                {activeTab === 'traffic' && (
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 relative z-10">
                        {report.map(row => (
                            <div
                                key={row.Link_ID}
                                onClick={() => setSelectedImage(`${API_BASE_URL}/images/link_${row.Link_ID}_traffic.png`)}
                                className="bg-white/50 dark:bg-royal-900/20 rounded-3xl p-4 border border-emerald-500/5 group hover:border-emerald-500/20 transition-all cursor-pointer hover:scale-[1.02]"
                            >
                                <div className="mb-4 flex justify-between items-center">
                                    <span className="text-xs font-black uppercase text-emerald-900 dark:text-emerald-100">Link {row.Link_ID}</span>
                                    <span className="text-[10px] text-emerald-500 font-mono">Traffic Profile</span>
                                </div>
                                <div className="rounded-xl overflow-hidden shadow-lg aspect-video bg-black/5">
                                    <img
                                        src={`${API_BASE_URL}/images/link_${row.Link_ID}_traffic.png`}
                                        alt={`Link ${row.Link_ID} Traffic`}
                                        className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                                        onError={(e) => (e.currentTarget.style.display = 'none')}
                                    />
                                </div>
                            </div>
                        ))}
                    </div>
                )}

                {activeTab === 'loss' && (
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 relative z-10">
                        {report.map(row => (
                            <div
                                key={row.Link_ID}
                                onClick={() => setSelectedImage(`${API_BASE_URL}/images/link_${row.Link_ID}_loss_pattern.png`)}
                                className="bg-white/50 dark:bg-royal-900/20 rounded-3xl p-4 border border-emerald-500/5 group hover:border-emerald-500/20 transition-all cursor-pointer hover:scale-[1.02]"
                            >
                                <div className="mb-4 flex justify-between items-center">
                                    <span className="text-xs font-black uppercase text-emerald-900 dark:text-emerald-100">Link {row.Link_ID}</span>
                                    <span className="text-[10px] text-emerald-500 font-mono">Loss Correlation</span>
                                </div>
                                <div className="rounded-xl overflow-hidden shadow-lg aspect-video bg-black/5">
                                    <img
                                        src={`${API_BASE_URL}/images/link_${row.Link_ID}_loss_pattern.png`}
                                        alt={`Link ${row.Link_ID} Loss`}
                                        className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                                        onError={(e) => (e.currentTarget.style.display = 'none')}
                                    />
                                </div>
                            </div>
                        ))}
                    </div>
                )}

            </div>

            {/* Lightbox Modal */}
            {selectedImage && (
                <div
                    className="fixed inset-0 z-[100] bg-black/90 backdrop-blur-md flex items-center justify-center p-8 animate-in fade-in duration-200"
                    onClick={() => setSelectedImage(null)}
                >
                    <img
                        src={selectedImage}
                        alt="Enlarged analysis"
                        className="max-w-full max-h-full rounded-2xl shadow-2xl border border-white/10"
                    />
                    <div className="absolute top-8 right-8 text-white/50 text-xs font-mono uppercase tracking-widest">
                        Click anywhere to close
                    </div>
                </div>
            )}
        </div>
    );
};

export default ReportView;
